AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'

Metrics/MethodLength:
  Max: 25

Layout/LineLength:
  Max: 120

Style/OneClassPerFile:
  Exclude:
    - 'spec/**/*'
    - 'examples/**/*'

Lint/UnusedBlockArgument:
  Exclude:
    - 'spec/**/*'

Naming/VariableNumber:
  Exclude:
    - 'spec/**/*'
    - 'examples/**/*'

AllCops:
  Exclude:
    - 'internal/**/*'

Metrics/ClassLength:
  Max: 130

Metrics/AbcSize:
  Max: 30

Metrics/ParameterLists:
  Max: 11
  MaxOptionalParameters: 9

Style/FormatStringToken:
  Enabled: false
